#Creperie    
 
cmm_site_page_creperie_presentation:
    pattern: /la-creperie/presentation
    defaults: { _controller: CmmSiteBundle:Site:pages }
cmm_site_page_creperie_quartier:
    pattern: /la-creperie/le-quartier
    defaults: { _controller: CmmSiteBundle:Site:pages }  
cmm_site_page_creperie_moment:
    pattern: /la-creperie/en-ce-moment
    defaults: { _controller: CmmSiteBundle:Site:pages }    
    
#Nos produits
cmm_site_page_produits:
    pattern: /nos-produits
    defaults: { _controller: CmmSiteBundle:Site:pages }
  
#La carte
cmm_site_page_carte_crepes_galettes:
    pattern: /la-carte/nos-crepes-et-galettes
    defaults: { _controller: CmmSiteBundle:Site:pages }    
cmm_site_page_carte_formules:
    pattern: /la-carte/les-formules
    defaults: { _controller: CmmSiteBundle:Site:pages }    

#Accès    
cmm_site_page_acces:
    pattern: /acces
    defaults: { _controller: CmmSiteBundle:Site:pages }    

#Contact
cmm_site_page_contact:
    pattern: /contact
    defaults: { _controller: CmmSiteBundle:Site:contact }
    

    
    
    
