   
cmm_site:
    resource: "@CmmSiteBundle/Resources/config/routing.yml"
    prefix:   /
    
cmm_site_pages:
    resource: "@CmmSiteBundle/Resources/config/pages.yml"

_console:
    resource: "@CoreSphereConsoleBundle/Resources/config/routing.yml"
    prefix: /_console